/*CRIANDO O BANCO DE DADOS*/
CREATE DATABASE IF NOT EXISTS cadastro; 
/*USANDO O BANCO DE DADOS CRIADO*/
USE cadastro;
/*CRIANDO A TABELA USUARIO NO BANCO DE DADOS*/
CREATE TABLE IF NOT EXISTS `cadastro`.`usuario` (
  `Usuario_id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `pessoa` VARCHAR(45) NOT NULL,
  `data_cadastro` DATETIME NOT NULL,
  PRIMARY KEY (`Usuario_id`)) DEFAULT CHARSET=utf8mb4;
/*Garantindo pelo SQL que não haja mais de uma conta com o mesmo email*/
ALTER TABLE usuario ADD UNIQUE (email);
/*CRIANDO A TABELA DOS LIVROS*/
CREATE TABLE IF NOT EXISTS `livrosc` (
  `id` int not null auto_increment ,
  `user` varchar(50) NOT NULL,
  `autor` varchar(50) NOT NULL,
  `titulo` varchar(50) NOT NULL,
  `editora` varchar(20) NOT NULL,
  `imgurl` varchar(1000) NOT NULL,
  `sinopse` varchar(2000) NOT NULL,
  primary key (id)
) DEFAULT CHARSET=utf8mb4 ENGINE=InnoDB AUTO_INCREMENT=13;
/*INSERINDO LIVROS DE EXEMPLO PARA TESTE*/
INSERT INTO `livrosc` (`user`, `autor`, `titulo`, `editora`, `imgurl`, `sinopse`) VALUES
	('user1@exemplo.com', 'Rachael Lippincott', 'A Cinco Passos de Você', 'Alt', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7bigV6oYPI23buODLxiAV17FV21sqzbkRTuTM0VG2nNvUAkNmxR97-CER2AF77TdHajqQa4XI&usqp=CAc', 'Stella Grant gosta de estar no controle. Ela parece ser uma adolescente típica, mas em sua rotina há listas de tarefas e inúmeros remédios que ela deve tomar para controlar a fibrose cística, uma doença crônica que impede que seus pulmões funcionem como deveriam. Suas prioridades são manter seus pais felizes e conseguir um transplante – e uma coisa não existe sem a outra. Mas para ganhar pulmões novos, Stella precisa seguir seu tratamento à risca e eliminar qualquer chance de infecção, o que significa que ela não pode ficar a menos que dois metros de distância – ou seis passos – de outros pacientes com a doença. O primeiro item é fácil para ela, mas o segundo pode se provar mais difícil do que ela esperava. O único controle que Will Newman deseja é o de sua própria vida. Ele não dá a mínima para o novo tratamento experimental para o qual foi selecionado e não aguenta mais a pressão de sua mãe para que melhore. Prestes a completar dezoito anos, ele mal pode esperar para finalmente se livrar das máquinas e hospitais, usando o pouco de vida que ainda lhe resta para conhecer o mundo. Stella e Will são muito diferentes. Ao mesmo tempo, a doença que os une não é a única coisa que têm em comum. Eles têm que ficar a seis passos um do outro, mas, conforme a conexão entre os dois aumenta, a vontade de burlar a distância física parece insuportável. Um grande amor vale um passo roubado?'),
	('user1@exemplo.com', 'Kiera cass', 'A Seleção', 'Seguinte', 'https://lojasaraiva.vteximg.com.br/arquivos/ids/6993791-287-426/780220.jpg?v=637075499365830000', 'Para trinta e cinco garotas, a “Seleção” é a chance de uma vida. Num futuro em que os Estados Unidos deram lugar ao Estado Americano da China, e mais recentemente a Illéa, um país jovem com uma sociedade dividida em castas, a competição que reúne moças entre dezesseis e vinte anos de todas as partes para decidir quem se casará com o príncipe é a oportunidade de escapar de uma realidade imposta a elas ainda no berço. É a chance de ser alçada de um mundo de possibilidades reduzidas para um mundo de vestidos deslumbrantes e joias valiosas. De morar em um palácio, conquistar o coração do belo príncipe Maxon e um dia ser a rainha. Para America Singer, no entanto, uma artista da casta Cinco, estar entre as Selecionadas é um pesadelo. Significa deixar para trás Aspen, o rapaz que realmente ama e que está uma casta abaixo dela. Significa abandonar sua família e seu lar para entrar em uma disputa ferrenha por uma coroa que ela não quer. E viver em um palácio sob a ameaça constante de ataques rebeldes. Então America conhece pessoalmente o príncipe. Bondoso, educado, engraçado e muito, muito charmoso, Maxon não é nada do que se poderia esperar. Eles formam uma aliança, e, aos poucos, America começa a refletir sobre tudo o que tinha planejado para si mesma — e percebe que a vida com que sempre sonhou talvez não seja nada comparada ao futuro que ela nunca tinha ousado imaginar.'),	
    ('user28@exemplo.com', 'Clare Vanderpool', 'Em Algum Lugar Nas Estrelas', 'Darkside', 'https://lojasaraiva.vteximg.com.br/arquivos/ids/4602202/1008900989.jpg?v=637054626553270000', 'Em Algum Lugar nas Estrelas, da autora norte-americana Clare Vanderpool, é um romance intenso sobre a difícil arte de crescer em um mundo que nem sempre parece satisfeito com a nossa presença. Pelo menos é desse jeito que as coisas têm acontecido para Jack Baker. A Segunda Guerra Mundial estava no fim, mas ele não tinha motivos para comemorar. Sua mãe morreu e seu pai... bem, seu pai nunca demonstrou se preocupar muito com o filho. Jack é então levado para um internato no Maine (o mesmo estado onde vivem Stephen King e boa parte de seus personagens). O colégio militar, o oceano que ele nunca tinha visto, a indiferença dos outros alunos: tudo aquilo faz Jack se sentir pequeno. Até ele conhecer o enigmático Early Auden. Early, um nome que poderia ser traduzido como precoce, é uma descrição muito adequada para um prodígio como ele, que decifra casas decimais do número Pi como se lesse uma odisseia. Mas, por trás de sua genialidade, há uma enorme dificuldade de se relacionar com o mundo e de lidar com seus sentimentos e com as pessoas ao seu redor. Quando chegam as festas de fim de ano, a escola fica vazia. Todos os alunos voltam para casa, para celebrar com suas famílias. Todos, menos Jack e Early. Os dois aproveitam a solidão involuntária e partem em uma jornada ao encontro do lendário Urso Apalache. Nessa grande aventura, vão encontrar piratas, seres fantásticos e até, quem sabe, uma maneira de trazer os mortos de volta – ainda que talvez do que Jack mais precise seja aprender a deixá-los em paz. Clare Vanderpool foi a primeira autora estreante a receber o cobiçado prêmio Newbery Medal, da American Library Association, por Moon Over Manifest, seu livro de estreia. Em Algum Lugar nas Estrelas é seu segundo romance. Comparado a clássicos como Huckleberry Finn, de Mark Twain, Em Algum Lugar nas Estrelas entrou na lista dos mais vendidos do New York Times e vem sendo adotado como um livro indispensável por várias escolas nos Estados Unidos. Uma leitura encantadora para leitores de todas as idades.'),
	('user36@exemplo.com', 'Becky Albertalli', 'Com Amor, Simon', 'Intrínseca', 'https://upload.wikimedia.org/wikipedia/pt/6/67/Love%2C_Simon.jpg', 'Encantadora história de amor que questiona os padrões sociais chega aos cinemas em 22 de março Com nova capa e novo título, a apaixonante história de Simon conquistou milhares de leitores com uma trama que trata com naturalidade e bom humor a afirmação e os dilemas de um adolescente gay. Agora, a adaptação do romance chega às telas de cinema com Nick Robinson, de Jurassic World, no papel de Simon, e Katherine Langford, protagonista de 13 Reasons Why. Simon Spier tem dezesseis anos e é gay, mas não conversa sobre isso com ninguém. Ele não vê problemas em sua orientação sexual, mas rejeita a ideia de ter que ficar dando explicação para as pessoas — afinal, por que só os gays têm que se apresentar ao mundo? Enquanto troca e-mails com um garoto misterioso que se identifica como Blue, Simon vai ter que enfrentar, além de suas dúvidas e inseguranças, uma chantagem inesperada. • Grande aposta da Twentieth Century Fox, o trailer do filme alcançou mais de 2 milhões de visualizações no YouTube em apenas 3 dias. Assista aqui: http://bit.ly/2jDfoSD “O filme captura perfeitamente a essência da história de Simon. Estou completamente apaixonada e sei que todos vão adorar.” Becky Albertalli'),
	('user9@exemplo.com', 'John Green', 'Quem é você Alasca', 'Intrínseca', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtPknpLwMafQKni5UCYg5kakXWzkiT5LG3xIFptkW7Oz1epoIxznBgGy65eZhmY-B3JEjW4oQ&usqp=CAc', 'Miles Halter tem fascinação pelas últimas palavras que grandes pessoas disseram antes de morrer. Vive de devorar biografias. Mas está cansado de ter só isso para livrá-lo do tédio que é a vida com os pais, na Flórida. Em busca do que o poeta François Rabelais chamou em suas últimas palavras de o “Grande Talvez”, Miles sai de casa para ingressar na Escola Culver Creek, um internato no Alabama. Muitas coisas o esperam lá; entre elas, Alasca Young. Inteligente, engraçada, louca e incrivelmente sexy, Alasca vai arrastar Miles para seu labirinto e catapultá-lo sem misericórdia na direção do Grande Talvez.'),
	('user7@exemplo.com', 'Jennifer L. Armentrout', 'Se Não Houver Amanhã', 'Universo dos Livros', 'https://images-na.ssl-images-amazon.com/images/I/51v+bCLrhtL._SX339_BO1,204,203,200_.jpg', 'Da autora best-seller Jennifer L. Armentrout, de Obsidiana (Saga Lux), este romance genuíno retrata as conseqüências de cada pequena decisão... Lena Wise está sempre ansiosa pelo dia seguinte, especialmente porque está começando o último ano da escola. Ela está decidida a passar o máximo de tempo possível com os amigos, completar as inscrições da faculdade e talvez informar seu melhor amigo de infância, Sebastian, sobre o que realmente sente por ele. Para Lena, o próximo ano vai ser épico — um ano de oportunidades e conveniências. Até que uma escolha, um instante… destrói tudo. Agora Lena não está ansiosa pelo dia seguinte. Não quando o tempo que dedica aos amigos pode nunca mais ser o mesmo. Não quando as inscrições para a faculdade podem ser qualquer coisa, menos viáveis. Não quando há o risco de Sebastian jamais perdoá-la pelo que aconteceu. Pelo que ela permitiu que acontecesse. À medida que sua culpa aumenta, Lena está ciente de que sua única esperança é superar o ocorrido. Mas como é possível seguir em frente quando a existência inteira, tanto dela quanto a de seus amigos, foi transformada? Como seguir em frente quando o amanhã sequer é garantido?'),
    ('user12@exemplo.com', 'Victoria Aveyard', 'Rainha Vermelha', 'Seguinte', 'https://lojasaraiva.vteximg.com.br/arquivos/ids/12054910/1008976886.jpg?v=637141926959370000', 'O mundo de Mare Barrow é dividido pelo sangue: vermelho ou prateado. Mare e sua família são vermelhos: plebeus, humildes, destinados a servir uma elite prateada cujos poderes sobrenaturais os tornam quase deuses. Mare rouba o que pode para ajudar sua família a sobreviver e não tem esperanças de escapar do vilarejo miserável onde mora. Entretanto, numa reviravolta do destino, ela consegue um emprego no palácio real, onde, em frente ao rei e a toda a nobreza, descobre que tem um poder misterioso… Mas como isso seria possível, se seu sangue é vermelho? Em meio às intrigas dos nobres prateados, as ações da garota vão desencadear uma dança violenta e fatal, que colocará príncipe contra príncipe — e Mare contra seu próprio coração.'),
    ('user73@exemplo.com', 'Stephen King', 'Sob a Redoma', 'Suma', 'https://images-submarino.b2w.io/produtos/imagens/111949294/111949307_1SZ.jpg', 'Um campo de força se materializa subitamente em uma cidade do Maine, isolando do resto do mundo as pessoas sob a redoma. O livro narra os conflitos, ações e reações dos presos, que em meio ao caos também se perguntam quem ou o quê está por trás do acontecimento.'),	
    ('user89@exemplo.com', 'Mary Shelley', 'Frankenstein', 'Lackington', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREdVreVpmMP2WRh_FjLp-Yfu-QDfgcBs70FFq6K5l3CLjdLOBvxeVUk1d664YnI3BVZgdSGpxW&usqp=CAc', 'Victor Frankenstein desde muito jovem se dedicou aos estudos da filosofia e das ciências naturais. Até que, em uma experiência bem-sucedida (que lhe sugou a energia e o afastou do convívio dos seus entes queridos), ele foi capaz de dar vida a um ser de feições e trejeitos assustadores. A partir de então, criador e criatura passam a viver um jogo de perseguição repleto de sangue e horror – a primeira obra de ficção científica da literatura e um clássico do terror.'),
	('user17@exemplo.com', 'Delia Owens', 'Um Lugar Bem Longe Daqui', 'Intrínseca', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQN0wxc3VtwXup4k2vDlJgjACERkJxv98hPx8bzisBt-yPMzMK1eXejmxlMViu7lqZ584cgHqM&usqp=CAc', 'Fenômeno editorial, com mais de 2 milhões de cópias vendidas, Um lugar bem longe daqui figura nas listas de best-sellers dos Estados Unidos desde seu lançamento original, em agosto de 2018. Por anos, boatos sobre Kya Clark, a “Menina do Brejo”, assombraram Barkley Cove, uma calma cidade costeira da Carolina do Norte. Ela, no entanto, não é o que todos dizem. Sensata e inteligente, Kya sobreviveu por anos sozinha no pântano que chama de lar, tendo as gaivotas como amigas e a areia como professora. Abandonada pela mãe, que não conseguiu suportar o marido abusivo e alcoólatra, e depois pelos irmãos, a menina viveu algum tempo na companhia negligente e por vezes brutal do pai, que acabou também por deixá-la. Anos depois, quando dois jovens da cidade ficam intrigados com sua beleza selvagem, Kya se permite experimentar uma nova vida — até que o impensável acontece e um deles é encontrado morto. Ao mesmo tempo uma ode à natureza, um emocionante romance de formação e uma surpreendente história de mistério, Um lugar bem longe daqui relembra que somos moldados pela criança que fomos um dia e que estamos todos sujeitos à beleza e à violência dos segredos que a natureza guarda. A obra foi incluída no clube de livros de Reese Witherspoon, que posteriormente adquiriu os direitos de adaptação cinematográfica e vai produzir o filme com a Fox 2000.'),
	('user34@exemplo.com', 'Rainbow Rowell', 'Eleanor & Park', 'Novo Século', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQfZIyFr0VxqRDoezSylKnl2Cy8P5DdlRc8ghvUyIoF4Q6LTRLLEU8oo0TaA7FWUSfaYpR15lb&usqp=CAc', 'Uma das maiores obras da literatura jovem contemporânea em nova edição. Eleanor é nova na cidade. Com roupas inusitadas, cachos ruivos indomáveis e uma família problemática, ela sente que nunca vai conseguir se encaixar. Park senta sozinho no ônibus da escola. Sempre de camiseta preta, fones de ouvido e a cabeça enfiada num livro, acha que consegue passar despercebido. Mas não para Eleanor. Aos poucos, entre fitas cassetes gravadas, pilhas de histórias em quadrinhos e conversas até tarde da noite, Eleanor e Park se apaixonam. Narrada durante o ano letivo de 1986, essa é a história de dois jovens de dezesseis anos que, mesmo sabendo que o primeiro amor quase nunca é para sempre, têm coragem e esperança suficientes para tentar. ?Eleanor & Park me lembrou não só como é ser jovem e se apaixonar por uma garota, mas como é ser jovem e se apaixonar por um livro.? ? John Green, autor de A culpa é das estrelas * Best-seller do New York Times. * Livro de honra do Michael L. Printz Award (2014). * Vencedor do Boston Globe-Horn Book Award de melhor livro de ficção (2013). * Escolhido como um dos melhores livros juvenis pela Publishers Weekly (2013). * Escolhido como um dos melhores livros juvenis pelo New York Times Book Review (2013).'),
	('user59@exemplo.com', 'Sarah J. Maas', 'Corte de Espinhos e Rosas', 'Galera', 'https://livrariascuritiba.vteximg.com.br/arquivos/ids/1908714-525-525/LV389070.jpg?v=637262208459900000', 'Ela roubou uma vida. Agora deve pagar com o coração. Nesse misto de A Bela e A Fera e Game of Thrones, Sarah J. Maas cria um universo repleto de ação, intrigas e romance. Depois de anos sendo escravizados pelas fadas, os humanos conseguiram se libertar e coexistem com os seres místicos. Cerca de cinco séculos após a guerra que definiu o futuro das espécies, Feyre, filha de um casal de mercadores, é forçada a se tornar uma caçadora para ajudar a família. Após matar uma fada zoomórfica transformada em lobo, uma criatura bestial surge exigindo uma reparação. Arrastada para uma terra mágica e traiçoeira — que ela só conhecia através de lendas —, a jovem descobre que seu captor não é um animal, mas Tamlin, senhor da Corte Feérica da Primavera. À medida que ela descobre mais sobre este mundo onde a magia impera, seus sentimentos por Tamlin passam da mais pura hostilidade até uma paixão avassaladora. Enquanto isso, uma sinistra e antiga sombra avança sobre o mundo das fadas e Feyre deve provar seu amor para detê-la... ou Tamlin e seu povo estarão condenados.');
